#!/bin/bash
#
# Nix package manager
#
# Installs nix package manager for command line software

source helpers

if test ! $(which nix-env); then
  info 'Installing Nix'
  sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
fi

if test ! $(which darwin-rebuild); then
  info 'Installing nix-darwin to control MacOS'
  nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
  ./result/bin/darwin-installer
fi
