#!/bin/bash
#
# Nix package manager
#
# Installs nix package manager for command line software

source helpers

if ! command_exists nix-env; then
  info 'Installing nix package manager'
  sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
else
  info "Skipping nix installation"
fi

if ! command_exists darwin-rebuild; then
  info 'Installing nix-darwin to control MacOS'
  nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
  ./result/bin/darwin-installer
else
  info "Skipping nix-darwin installation"
fi

if [ -z "$(nix-channel --list | grep home-manager)" ]; then
  info 'Installing nix home-manager'
  nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
  nix-channel --update
else
  info 'Skipping nix home-manager installation'
fi

exit 0
