#!/bin/sh

source print_helper

if test ! $(which npm)
then
  info "Installing npm..."
  brew install npm

  info "Installing npm packages..."
  (
    export PKG=eslint-config-airbnb-base;
    npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install -g "$PKG"
  )
fi

exit 0
