#!/bin/sh

source print_helper

info "Installing npm..."
brew install node npm
npm update npm -g

info "Installing npm packages..."
npm install -g eslint-config-airbnb-base eslint
npm install -g eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react

npm install -g bower
npm install -g ember ember-cli

exit 0
