#!/bin/sh
source helpers

ensure_command_exists gem

gem install bundler

if command_exists gem; then
  info "Setting up rubygems config files"
  current_dir # Sets $CURRENT_DIR variable
  link_all_files "$CURRENT_DIR"
fi
