#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

ensure_command_exists ruby
ensure_command_exists gem

info "Setting up ruby package"
gem install bundler
run_required_step "Stowing ruby package" stow ruby

exit 0
