#!/bin/bash

source "$DOTFILES_ROOT/helpers"

ensure_command_exists python
ensure_command_exists pip
# TODO Ensure $PYENV_ROOT exists command

python -m pip install aider-install
"$PYENV_ROOT/shims/aider-install"
