#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

ensure_command_exists git

info "Setting up git config and ignore files"
run_required_step "Stowing git package" stow git

exit 0
