#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

for file in "$@"; do
  brewfile_path="$DOTFILES_ROOT/homebrew/Brewfiles/$file"

  if [ -f "$brewfile_path" ]; then
    run_required_step "Installing homebrew packages for profile $file" brew bundle --file="$brewfile_path"
  else
    fail "Bundle $brewfile_path not found."
  fi
done
