#!/bin/bash

source "$DOTFILES_ROOT/helpers"

for file in "$@"; do
  info "Installing homebrew packages for profile $file"
  brewfile_path="$DOTFILES_ROOT/homebrew/Brewfiles/$file"

  if [ -f "$brewfile_path" ]; then
    brew bundle --file="$brewfile_path"
  else
    fail "Bundle $brewfile_path not found."
  fi
done
