#!/bin/bash

source "$DOTFILES_ROOT/print_helper"

link_files () {
  ln -sf "$1" "$2"
  success "Linked $1 to $2"
}

current_dir () {
  CURRENT_DIR="$(cd "$(dirname "$0")" && pwd)"
  echo "$CURRENT_DIR"
}

link_all_files () {
  local directory=$1

  for source in `find $directory -maxdepth 1 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source%.*}\"`"
    link_files "$source" "$dest"
  done
}

command_exists () {
  command -v "$1" &> /dev/null
}

ensure_command_exists () {
  if ! command_exists "$1"
  then
    fail "Command line '$1' not found"
  fi
}

bundle_current_dir() {
  brew bundle --file="$(current_dir)/Brewfile"
}

current_profile() {
  if [ -f "$DOTFILES_ROOT/.current_profile" ]; then
    current_profile=$(head -n 1 "$DOTFILES_ROOT/.current_profile")
    echo "$current_profile"
  fi
}
