#!/usr/bin/env bash
#
# Installation process

source helpers

DOTFILES_ROOT=$(pwd -P)

# Install some essential softwares
packages=(osx terminal.app homebrew git zsh essentials tmux vim)
for package in "${packages[@]}"; do
  info "Setting up $package package..."
  $DOTFILES_ROOT/$package/install
done
unset file

success 'All done! :D'

exit 0
