#!/bin/bash

# Source all rc files found inside packages that are being used
while read package; do
  if [ -f $DOTFILES_ROOT/$package/rc ]
  then
    source $DOTFILES_ROOT/$package/rc
  fi
done < "$DOTFILES_ROOT/packages"
unset package
