#!/bin/bash

# Updates dotfiles
git -C "$HOME/.dotfiles" pull --rebase

# Packages eligible for update
packages=("zsh" "emacs" "homebrew" "vim" "tmux")
for package in "${packages[@]}"; do
  "$DOTFILES_ROOT/$package/update"
done
