#!/bin/bash

# Updates dotfiles
git -C "$HOME/.dotfiles" pull --rebase

function update_package() {
  "$DOTFILES_ROOT/$1/update"
}

update_package "zsh"
update_package "emacs"
update_package "homebrew"
update_package "vim"
update_package "tmux"
