#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

info "Setting up logseq"
run_required_step "Stowing logseq package" stow logseq

warning "Ask Logseq to install plugins from file at Plugin page."
