#!/bin/bash
source helpers

ensure_command_exists brew

info "Installing Chunkwm Window Manager"

brew tap koekeishiya/formulae
brew install chunkwm

current_dir # Sets $CURRENT_DIR variable
link_all_files $CURRENT_DIR

### TODO: Call skhd instal script from here

# codesign -fs "chunkwm-cert" /usr/local/opt/chunkwm/bin/chunkwm

# To manipulate desktops you need to do some operations on macos recovery mode
# 1. Restart Mac and hold cmd + r during initialization
# 2. Open Terminal.app
# 3. `csrutil disable`
# 4. Restart Mac again
# 5. `sudo chunkwm --install-sa`
# 6. `chunkwm --load-sa`

exit 0
