#!/bin/sh

source print_helper

if test $(which brew)
then
  info 'Installing dev environment...'
  brew install gpgme graphviz phantomjs icu4c

  info 'Setup brew-services'
  brew tap homebrew/services

  mkdir -p $HOME/Library/LaunchAgents

  info 'Installing Atom'
  brew cask install atom

  info 'Setup postgresql'
  brew install postgresql95
  createuser postgres
  psql -d postgres -c "ALTER USER postgres WITH SUPERUSER;"
  createuser lucas
  psql -d postgres -c "ALTER USER lucas WITH SUPERUSER;"

  info 'Setup mongodb'
  brew install mongodb
  ln -sfv /usr/local/opt/mongodb/*.plist $HOME/Library/LaunchAgents
  launchctl load $HOME/Library/LaunchAgents/homebrew.mxcl.mongodb.plist

  info 'Setup elasticsearch'
  brew install elasticsearch
  ln -sfv /usr/local/opt/elasticsearch14/*.plist $HOME/Library/LaunchAgents
  launchctl load $HOME/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist

  info 'Setup redis'
  brew install redis
  ln -sfv /usr/local/opt/redis/*.plist $HOME/Library/LaunchAgents
  launchctl load $HOME/Library/LaunchAgents/homebrew.mxcl.redis.plist

  info 'Setup heroku'
  brew install heroku-toolbelt

  info 'Install essential tools'
  brew install coreutils htop ag tree

  info 'Setup Gist'
  brew install gist
  gist --login
fi

exit 0
