#!/bin/bash

brew install cursor

cursor --install-extension vscodevim.vim # Vim
cursor --install-extension danprince.vsnetrw # oil.nvim / netrw / vim-vinegar
cursor --install-extension chaitanyashahare.lazygit # Better git
cursor --install-extesiion shd101wyy.markdown-preview-enhanced # Markdown preview

# Clojure extensions
cursor --install-extension betterthantomorrow.calva
cursor --install-extension betterthantomorrow.calva-spritz
