#!/bin/sh
source helpers

ensure_command_exists brew

if ! command_exists vim; then
  brew install vim
else
  info 'Skipping vim'
fi

if [ ! -d "$HOME/.vim" ]; then
  info 'Installing vim-plug + plugins'
  curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  vim +PlugInstall +qall
else
  info 'Skipping vim plugins'
fi

exit 0
