#!/bin/bash
source helpers

if [ -d "$HOME/.vim" ]; then
  info 'Installing vim-plug + plugins'
  curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  vim +PlugInstall +qall
else
  info 'Skipping vim plugins'
fi

if [ -d "$HOME/.vim" ]; then
  # Create temp files folder
  mkdir -p "$HOME/.vim/_backup" "$HOME/.vim/_temp"

  current_dir # Sets $CURRENT_DIR variable
  link_all_files "$CURRENT_DIR"

  # Creates undodir to store files undo history
  mkdir -p "$HOME/.vim/undodir/"
fi

exit 0
