#!/bin/bash

source helpers

EDITOR=${1:-"nvim"} # Receive editor as argument but uses nvim by default

# Set CONFIG_DIR according to editor
if [ "$EDITOR" = "vim" ]; then
  CONFIG_DIR="$HOME/.vim"
elif [ "$EDITOR" = "nvim" ]; then
  CONFIG_DIR="$HOME/.config/nvim"
else
  fail "Editor not recognized. Please use 'vim' or 'nvim'."
fi

if [ ! -d "$CONFIG_DIR" ]; then
  info "Setting up config directory $CONFIG_DIR"
  mkdir "$CONFIG_DIR"

  if [ "$EDITOR" = "nvim" ]; then
    link_files "$(current_dir)/.vimrc" "$CONFIG_DIR/init.vim"
  elif [ "$EDITOR" = "vim" ]; then
    stow vim
  fi
fi

# Create backup, temp files and persistent undo folder
# Using .vim because of sensible configurations
mkdir -p "$HOME/.vim/_backup" "$HOME/.vim/_temp" "$HOME/.vim/undodir/"

info 'Installing vim-plug + plugins'
"$EDITOR" +PlugInstall +qall


if [ "$EDITOR" = "nvim" ]; then
  if command_exists 'pip'; then
    pip install neovim
  fi

  if command_exists 'pip3'; then
    pip3 install neovim
  fi

  if command_exists 'npm'; then
    npm install -g neovim
  fi
fi

success "$EDITOR configuration completed"

exit 0
