#!/bin/bash
source helpers

check_homebrew
current_dir # Sets $CURRENT_DIR variable

if [ ! -d "$HOME/.vim" ]
then
  $CURRENT_DIR/../vim/install
fi

info 'Installing Neovim'
brew install neovim

ensure_command_exists 'pip'
pip install --upgrade pip
pip install neovim

ensure_command_exists 'pip3'
pip3 install neovim

ensure_command_exists 'gem'
gem install neovim

ensure_command_exists 'npm'
npm install -g neovim

mkdir $HOME/.config
ln -s $HOME/.vim $HOME/.config/nvim
ln -s $HOME/.vimrc $HOME/.config/nvim/init.vim
