#!/bin/bash
source helpers

ensure_command_exists brew
current_dir # Sets $CURRENT_DIR variable

if [ ! -d "$HOME/.vim" ]; then
  info 'Installing vim package as dependency for neovim'
  "$CURRENT_DIR/../vim/install"
fi

if ! command_exists nvim; then
  brew install neovim
else
  info 'Skipping neovim'
fi

if command_exists 'pip'; then
  pip install --upgrade pip
  pip install neovim
fi

if command_exists 'pip3'; then
  pip3 install neovim
fi

if command_exists 'gem'; then
  gem install neovim
fi

if command_exists 'npm'; then
  npm install -g neovim
fi
