#!/bin/bash
source helpers

if command_exists 'pip'; then
  pip install --upgrade pip
  pip install neovim
fi

if command_exists 'pip3'; then
  pip3 install neovim
fi

if command_exists 'gem'; then
  gem install neovim
fi

if command_exists 'npm'; then
  npm install -g neovim
fi

if command_exists nvim; then
  mkdir "$HOME/.config"
  link_files "$HOME/.vim" "$HOME/.config/nvim"
  link_files "$HOME/.vimrc" '$HOME/.config/nvim/init.vim'
fi

exit 0
