#!/bin/bash
source helpers

if command_exists mix; then
  info "Installing hex package manager"
  yes | mix local.hex

  info "Installing Phoenix Framework"
  yes | mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez
fi

exit 0
