#!/bin/bash

source "$DOTFILES_ROOT/helpers"

info "Installing Rosetta to support Intel apps"
softwareupdate --install-rosetta --agree-to-license

# Based on https://github.com/mathiasbynens/dotfiles
# For more defaults: https://macos-defaults.com/

info "Setup up MacOS sensible configs"

# Close any open System Preferences panes, to prevent them from overriding
# settings were about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

### General UI/UX

info "Disable sound effects on boot"
sudo nvram SystemAudioVolume=" "

info "Disable block when software has no validation from apple"
spctl --master-disable

info "Remove duplicates in the 'Open With' menu (also see lscleanup alias)"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

info "Disable Resume system-wide"
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

info "Disable the “Are you sure you want to open this application?” dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false

info "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 2

### Trackpad, mouse, keyboard, Bluetooth accessories, and input

info "Setting scrollbar behavior"
defaults write NSGlobalDomain AppleShowScrollBars -string "Automatic"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

info "Trackpad: enable tap to click for this user and for the login screen"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

#info "Disable natural (Lion-style) scrolling"
#defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

info "Increase sound quality for Bluetooth headphones/headsets"
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

info "Set a blazingly fast keyboard repeat rate"
defaults write -g KeyRepeat -int 1 # ms
defaults write -g InitialKeyRepeat -int 10 # ms

#info "Set language and text formats"
#defaults write NSGlobalDomain AppleLanguages -array "en-BR"
#defaults write NSGlobalDomain AppleLocale -string "en_BR"
#defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
#defaults write NSGlobalDomain AppleMetricUnits -bool true

info "Stop iTunes from responding to the keyboard media keys"
launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

info "Disable press-and-hold for keys in favor of key repeat"
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

### Screen

info "Require password immediately after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

info "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
defaults write com.apple.screencapture type -string "png"

info "Enable subpixel font rendering on non-Apple LCDs"
# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
defaults write NSGlobalDomain AppleFontSmoothing -int 1

info "Enable HiDPI display modes (requires restart)"
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

### Finder

info "Set sidebar icon size to medium"
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

info "Set $HOME as default location for new Finder windows"
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

info "Show icons for hard drives, servers, and removable media on the desktop"
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

info "Finder: show all filename extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

info "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

info "Finder: show path bar"
defaults write com.apple.finder ShowPathbar -bool false

info "Finder: show status bar"
defaults write com.apple.finder ShowStatusBar -bool true

info "Keep folders on top when sorting by name"
defaults write com.apple.finder _FXSortFoldersFirst -bool true

info "When performing a search, search the current folder by default"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

info "Avoid creating .DS_Store files on network or USB volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

info "Use list view in all Finder windows by default"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

info "Automatically open a new Finder window when a volume is mounted"
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

### Dock

user "Do you want to remove all dock icons? (y/n)"
read WIPE_ALL_DOCK

if [[ $WIPE_ALL_DOCK = "y" ]]; then
  # Wipe all (default) app icons from the Dock
  # This is only really useful when setting up a new Mac, or if you don't use
  # the Dock to launch apps.
  defaults write com.apple.dock persistent-apps -array
fi

info "Dock: Setup minimize effect to genie"
defaults write com.apple.dock "mineffect" -string "genie"

info "Dock: Set dock position to bottom"
defaults write com.apple.dock "orientation" -string "bottom"

info "Dock: Set the icon size of Dock items to 64 pixels"
defaults write com.apple.dock tilesize -int 64

info "Dock: Setup dock autohide"
defaults write com.apple.dock "autohide" -bool "true" # Enable
defaults write com.apple.dock "autohide-time-modifier" -float "0.5" # Animation time
defaults write com.apple.dock "autohide-delay" -float "0.1" # Delay to show

info "Dock: Show indicator lights for open applications in the Dock"
defaults write com.apple.dock show-process-indicators -bool true

info "Dock: Show recent applications "
defaults write com.apple.dock show-recents -bool false

### Mission Control

info "Speed up Mission Control animations"
defaults write com.apple.dock expose-animation-duration -float 0.1

info "Don’t group windows by application in Mission Control"
defaults write com.apple.dock "expose-group-apps" -bool "false"

info "Don’t automatically rearrange Spaces based on most recent use"
defaults write com.apple.dock mru-spaces -bool false

### Terminal.app

info "Only use UTF-8 in Terminal.app"
defaults write com.apple.terminal StringEncodings -array 4

info "Enable Secure Keyboard Entry in Terminal.app"
# See: https://security.stackexchange.com/a/47786/8918
defaults write com.apple.terminal SecureKeyboardEntry -bool true

info "Disable the annoying line marks"
defaults write com.apple.Terminal ShowLineMarks -int 0

### Activity Monitor

info "Show all processes in Activity Monitor"
defaults write com.apple.ActivityMonitor ShowCategory -int 0

### Mac App Store

info "Enable the automatic update check for Mac App Store"
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

info "Check for software updates daily, not just once per week"
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

info "Download newly available updates in background"
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

info "Install System data files & security updates"
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

info "Turn on app auto-update"
defaults write com.apple.commerce AutoUpdate -bool true

### Photos

info "Prevent Photos from opening automatically when devices are plugged in"
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

### Time Machine

info "Prevent Time Machine from prompting to use new hard drives as backup volume"
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

exit 0
