#!/bin/bash

source helpers

# noclamshell avoids keeping computer ON when using secondary display.
# It is a script that checks if computer lid is closed to put it to sleep.
brew install pirj/homebrew-noclamshell/noclamshell
brew services start noclamshell

exit 0
