#!/bin/sh
source helpers

check_homebrew

info 'Installing ElasticSearch'
brew install elasticsearch

info 'Setting up ElasticSearch LaunchAgent'
mkdir -p $HOME/Library/LaunchAgents
ln -sfv /usr/local/opt/elasticsearch/*.plist $HOME/Library/LaunchAgents
launchctl load $HOME/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist

exit 0
