#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

source helpers

# Check for Homebrew
if ! command_exists brew; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  info 'Setting up brew-services tap'
  brew tap homebrew/services
  brew services list
fi

exit 0
