#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

source helpers

# Check for Homebrew
if test ! $(which brew); then
  info 'Installing Homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  info 'Setup brew-services'
  brew tap homebrew/services

  info 'Installing brew-cask and install MacOS apps...'
  brew tap caskroom/cask
  brew tap caskroom/versions

  while read app; do
    brew cask install $app
  done < "`pwd`/homebrew/apps"
  unset app
fi

exit 0
