#!/bin/bash

DOTFILES_ROOT="${DOTFILES_ROOT:-"$(cd "$(dirname "$0")/.." && pwd -P)"}"
source "$DOTFILES_ROOT/helpers"

# Cask upgrades only make sense on macOS.
if is_macos; then
  export HOMEBREW_NO_UPGRADE_QUIT_CASKS=1
  brew cu --all --yes
fi

brew update
brew upgrade --yes
brew cleanup
