git:
  fetchAll: false
os:
  edit: '$HOME/.dotfiles/git/lazygit-open {{filename}}'
  editAtLine: 'LAZYGIT_LINE={{line}} $HOME/.dotfiles/git/lazygit-open {{filename}}'
  editAtLineAndWait: 'nvim +{{line}} -- "{{filename}}"'
customCommands:
  - key: '<c-t>'
    context: 'commits'
    description: 'View selected commit in Hunk'
    command: 'hunk show {{.SelectedCommit.Hash | quote}}'
    output: 'terminal'
  - key: '<c-t>'
    context: 'localBranches'
    description: 'View selected branch diff in Hunk'
    command: 'git diff --no-ext-diff "$(git merge-base {{.SelectedLocalBranch.Name | quote}} HEAD)" {{.SelectedLocalBranch.Name | quote}} | hunk patch'
    output: 'terminal'
