#!/usr/bin/env bash

function help {
cat <<EOF
Exports a table from a postgres database to a csv.gz file.
This is a brother script of imp_pg_table.

Usage: exp_pg_table <DB NAME> <DB USER> <TABLE NAME>

PS: The commands to import back these exports are:
$ psql -U <db user> -d <db name> < file.sql
$ gzip -cd <file.csv.gz> | psql -U <db user> -d <db name> -c "copy <table> from stdin csv header;"
EOF
}

if [ "$#" -lt 3 ]; then
  help
  exit 1
fi

# Params
DB=$1
USER=$2
TABLE=$3

# Exports table sql
echo "Exporting $TABLE schema."
pg_dump -U $USER --schema-only --no-tablespace --no-owner --table="$TABLE" -d "$DB" > "$TABLE.sql"

# Exports data to csv.gz
echo "Exporting $TABLE data."
psql -d $DB -c "copy $TABLE to stdout csv header;" | gzip > "$TABLE.csv.gz"
