#!/usr/bin/env bash

# Params
DB=$1
USER=$2
# $3, $4, ... = shp files that the tables are imported

function help {
cat <<EOF
shp_import imports a list of shape files to a postgres database.
Usage: shp_import <DB NAME> <DB USER> <SHP FILES>

Examples: shp_import brazil postgres ~/*.shp
EOF
}

# Import specified table to postgres
# Params: $1 = file name
function import {
  table=`basename $1 .shp`
  echo "Importing file $table.shp..."
  shp2pgsql -s 4326 -g geom -I -W LATIN1 $1 $table | psql -U $USER -d $DB > shp2pgsql.out
  unset table
}

if [ "$#" -lt 3 ]; then
  help
  exit 1
fi

# Creates postgis extension in database
psql -U $USER -d $DB -c "create extension if not exists postgis;"

# Iterates through all the params except the DB and USER
shift 2
for table_file in "$@"; do
  import $table_file
done
unset table_file

echo 'Done!'
