#!/bin/bash

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Set jupyter paths to avoid a bug when using magilla
# https://github.com/jupyter/nbclassic/issues/255
export JUPYTER_PATH=/opt/homebrew/share/jupyter
export JUPYTER_CONFIG_PATH=/opt/homebrew/etc/jupyter

# Add local bin to path for local installs (pipenv requirement)
export PATH=$PATH:$HOME/.local/bin
