#!/bin/sh
source helpers

ensure_command_exists pyenv

pyenv install 3.11.6
pyenv global 3.11.6

pip3 install notebook


# Install vim bindings into jupyter notebooks
# Create required directory in case (optional)
mkdir -p "$(jupyter --data-dir)/nbextensions"
# Clone the repository
cd "$(jupyter --data-dir)/nbextensions" || exit 1
git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding
# Activate the extension
jupyter nbextension enable vim_binding/vim_binding

exit 0
