#!/bin/sh
source helpers

ensure_command_exists pyenv

pyenv install 3.10.0
pyenv global 3.10.0

pip install --upgrade pip
pip install notebook nbclassic

# Vim bindings to Jupyter Notebooks
pip install jupyterlab-vim

exit 0
