#!/bin/sh
source helpers

ensure_command_exists pyenv
ensure_command_exists pip3
ensure_command_exists git

pyenv install 3.10.0
pip3 install notebook


# Install vim bindings into jupyter notebooks
# Create required directory in case (optional)
mkdir -p $(jupyter --data-dir)/nbextensions
# Clone the repository
cd $(jupyter --data-dir)/nbextensions
git clone https://github.com/lambdalisue/jupyter-vim-binding vim_binding
# Activate the extension
jupyter nbextension enable vim_binding/vim_binding

exit 0
