#!/bin/bash

source "$DOTFILES_ROOT/scripts/fzf-tmux-helpers.sh"

selected_dir=$(fzf_tmux_code_dir)

if [ "$selected_dir" ]; then
  base_dir=$(resolve_code_home)
  tmux new-window -a -c "$base_dir/$selected_dir"
fi
