#!/bin/bash
TITLE="${1:-Notification}"
MESSAGE="${2:-}"
ON_CLICK="${3:-}"

if [ -z "$MESSAGE" ]; then
  exit 0
fi

if [ -n "$ON_CLICK" ]; then
  terminal-notifier -title "$TITLE" -message "$MESSAGE" \
    -execute "osascript -e 'tell application \"kitty\" to activate'; $ON_CLICK"
else
  terminal-notifier -title "$TITLE" -message "$MESSAGE" \
    -activate "net.kovidgoyal.kitty"
fi
