#!/bin/bash
TITLE="${1:-Notification}"
MESSAGE="${2:-}"
ON_CLICK="${3:-}"

if [ -z "$MESSAGE" ]; then
  exit 0
fi

if [ -n "$ON_CLICK" ]; then
  /opt/homebrew/bin/terminal-notifier -title "$TITLE" -message "$MESSAGE" \
    -activate "net.kovidgoyal.kitty" \
    -execute "export PATH='/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin'; $ON_CLICK"
else
  /opt/homebrew/bin/terminal-notifier -title "$TITLE" -message "$MESSAGE" \
    -activate "net.kovidgoyal.kitty"
fi
