#!/bin/bash

source helpers

OPENAI_API_KEY=$(cat $HOME/.OPENAI_API_KEY)

if [ $# -lt 1 ]; then
  echo "Usage: $0 <file_path>"
  exit 1
fi

input_file=$1
extension="${input_file##*.}"

if [ "$extension" == "aac" ]; then
  info "AAC is not accepted by OpenAI, converting file to MP3."
  output_file="${input_file%.*}.mp3"
  ffmpeg -i "$input_file" -codec:a libmp3lame -qscale:a 2 "$output_file"
  input_file=$output_file
fi


info "Transcripting audio file to text."

curl --request POST \
  --url https://api.openai.com/v1/audio/transcriptions \
  --header "Authorization: Bearer $OPENAI_API_KEY" \
  --header 'Content-Type: multipart/form-data' \
  --form file=@"$input_file" \
  --form model=whisper-1

success "Transcription finished!"
