#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

OPENAI_API_KEY=$(cat $HOME/.OPENAI_API_KEY)

if [ $# -lt 1 ]; then
  echo "Usage: $0 <file_path> [output_file]"
  exit 1
fi

input_file=$1
extension="${input_file##*.}"

info "Converting file to MP3 to ensure transcription works."
output_file="${input_file%.*}.mp3"
ffmpeg -i "$input_file" -codec:a libmp3lame -qscale:a 2 "$output_file"
input_file=$output_file

info "Transcripting audio file to text."

text=$(curl --request POST \
  --url https://api.openai.com/v1/audio/transcriptions \
  --header "Authorization: Bearer $OPENAI_API_KEY" \
  --header 'Content-Type: multipart/form-data' \
  --form file=@"$input_file" \
  --form model=whisper-1 | jq -r .text)

if [ -n "$2" ]; then
  echo "$text" >> "$2"
  success "Transcription appended to $2"
else
  echo "$text"
  success "Transcription finished!"
fi
