#!/bin/bash

# TODO Migrate find to use fd (simpler and faster tool)
FILE=$(find . -type f -not -path '*/\.git/*' -not -path '*/\.idea/*' | fzf --preview "bat --color=always --style=numbers --line-range=:500 {}")

if [ "$FILE" ]
then
  nvim "$FILE"
fi

exit 0
