#!/bin/bash
source helpers

check_homebrew

info "Installing Karabiner to remap keyboard"

brew cask install karabiner-elements

current_dir # Sets $CURRENT_DIR variable
link_files $CURRENT_DIR/karabiner.json.symlink $HOME/.config/karabiner/karabiner.json

exit 0
