#!/bin/bash
source helpers

check_homebrew

info "Installing Karabiner to remap keyboard"

brew cask install karabiner-elements

current_dir # Sets $CURRENT_DIR variable
source "$CURRENT_DIR/cp-out-config.sh"

exit 0
