#!/bin/sh
source helpers

check_homebrew

info 'Setup brew-cask tap'
brew tap caskroom/cask
brew tap caskroom/versions

current_dir # Sets CURRENT_DIR var

while read app; do
  brew cask install $app
done < "$CURRENT_DIR/list"
unset app

exit 0
