#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

# reattach-to-user-namespace: Makes copying and pasting in Terminal.app work again on MacOS Sierra
# https://github.com/tmux/tmux/issues/543#issuecomment-248980734
# https://github.com/tmux/tmux/issues/543
if is_macos; then
  brew install tmux reattach-to-user-namespace
else
  brew install tmux
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  info "Installing tmux plugin manager"
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
fi

# Plugin installation happens in setup (after stow), when ~/.tmux.conf
# exists and the tmux server can resolve TMUX_PLUGIN_MANAGER_PATH.
