#!/bin/bash
source helpers

ensure_command_exists brew

if ! command_exists tmux; then
  brew install tmux

  # Makes copying and pasting in Terminal.app work again on MacOS Sierra
  # https://github.com/tmux/tmux/issues/543#issuecomment-248980734
  # https://github.com/tmux/tmux/issues/543
  brew install reattach-to-user-namespace

  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
else
  info 'Skipping tmux'
fi

exit 0
