#!/bin/bash

export DEFAULT_TMUX_SESSION_NAME="L"

tmux has-session -t "$DEFAULT_TMUX_SESSION_NAME" 2>/dev/null

if [[ -z "$TMUX" && $? != 0 ]]; then
  echo "Creating TMUX session"
  tmux new-session -s "$DEFAULT_TMUX_SESSION_NAME" -d &
fi

