#!/bin/bash
source helpers

if command_exists tmux; then
  # Install tmux plugins
  "$HOME/.tmux/plugins/tpm/scripts/install_plugins.sh"

  current_dir # Sets $CURRENT_DIR variable
  link_all_files "$CURRENT_DIR"
fi

exit 0
