#!/bin/bash

tmux start-server 2>/dev/null || true
tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/" 2>/dev/null || true
"$HOME/.tmux/plugins/tpm/bin/install_plugins"
"$HOME/.tmux/plugins/tpm/bin/update_plugins" all
"$HOME/.tmux/plugins/tpm/bin/clean_plugins"
