#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

info "Installing ZSH"
brew install zsh

# Install zinit package manager
if [ ! -d "$HOME/.local/share/zinit" ]; then
  info "Installing zinit package manager"
  # NO_EDIT is to avoid editting zshrc file
  NO_EDIT=1 bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
fi
