#!/bin/bash

source "$DOTFILES_ROOT/helpers"
bundle_current_dir

# Install zinit package manager
if [ ! -d "$HOME/.local/share/zinit" ]; then
  # NO_EDIT is to avoid editting zshrc file
  NO_EDIT=1 bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
fi
