#!/bin/bash

source helpers

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

  # Install better zsh-completions
  git clone https://github.com/zsh-users/zsh-completions "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"
else
  info 'Skipping zsh and oh-my-zsh'
fi

if command_exists zsh; then
  current_dir # Sets $CURRENT_DIR variable
  link_all_files "$CURRENT_DIR"
fi
