#!/bin/bash

source "$DOTFILES_ROOT/helpers"

# Execute zinit commands using zsh with the loaded configurations
zsh -c "
  # Load zinit configurations
  ZINIT_HOME=\"\${XDG_DATA_HOME:-\${HOME}/.local/share}/zinit/zinit.git\"
  [ -f \"\$ZINIT_HOME/zinit.zsh\" ] && source \"\$ZINIT_HOME/zinit.zsh\"

  # Execute update commands
  zinit self-update
  zinit update --parallel
"
