#!/bin/bash

source "$DOTFILES_ROOT/helpers"
bundle_current_dir

# Executar comandos zinit usando zsh com as configurações carregadas
zsh -c "
  # Carregar configurações do zinit
  ZINIT_HOME=\"\${XDG_DATA_HOME:-\${HOME}/.local/share}/zinit/zinit.git\"
  [ -f \"\$ZINIT_HOME/zinit.zsh\" ] && source \"\$ZINIT_HOME/zinit.zsh\"

  # Executar comandos de atualização
  zinit self-update
  zinit update --parallel
"
