#!/bin/bash
source helpers

check_homebrew

info "Installing Emacs"
brew tap d12frosted/emacs-plus
brew install --build-from-source emacs-plus --without-spacemacs-icon
cp -rf /usr/local/opt/emacs-plus/Emacs.app /Applications

git clone --branch develop https://github.com/hlissner/doom-emacs ~/.emacs.d

if [ ! -h $HOME/.doom.d ]; then
  current_dir
  ln -sf $CURRENT_DIR/doom.d.symlink $HOME/.doom.d
fi

EMACS_D="$HOME/.emacs.d"
$EMACS_D/bin/doom -y refresh
$EMACS_D/bin/doom -y upgrade
$EMACS_D/bin/doom -y update

exit 0
