#!/bin/bash
source helpers

ensure_command_exists brew
ensure_command_exists git

if ! command_exists emacs; then
  brew tap d12frosted/emacs-plus
  brew install emacs-plus@28 --with-native-comp
else
  info "Skipping emacs-plus"
fi

if [ ! -d "$HOME/.emacs.d" ]; then
  git clone --branch develop https://github.com/hlissner/doom-emacs "$HOME/.emacs.d"

  DOOM="$HOME/.emacs.d"
  "$DOOM/bin/doom" install
else
  info "Skipping doom-emacs"
fi

exit 0
