#!/bin/bash
source helpers

check_homebrew

brew install emacs

git clone --branch develop https://github.com/hlissner/doom-emacs ~/.emacs.d

current_dir
ln -sf $CURRENT_DIR/doom.d.symlink $HOME/.doom.d

EMACS_D="$HOME/.emacs.d"
$EMACS_D/bin/doom refresh

exit 0
