#!/bin/bash

source helpers

ensure_command_exists emacs
ensure_command_exists doom

if [ ! -d "$HOME/.doom.d" ]; then
  info "Setting up doom"
  current_dir
  link_files "$CURRENT_DIR/doom.d.symlink" "$HOME/.doom.d"
  doom -y sync

  doom env
else
  info 'Skipping doom setup'
fi

