#!/bin/bash

source "$DOTFILES_ROOT/print_helper"

# For Magit Forge to work, create a Personal Access Token in github
# https://github.com/settings/tokens
# Paste the token in `authinfo` right after password

info "Setting up Forge authinfo config"

gpg --output "$HOME/.authinfo.gpg" --symmetric "$(current_dir)/authinfo"
