#!/bin/bash

source helpers

ensure_command_exists emacs
ensure_command_exists doom

if [ ! -d "$HOME/.doom.d" ]; then
  info "Setting up doom"
  current_dir
  mv "$HOME/.config/doom" "$HOME/.config/doom.backup"
  link_files "$CURRENT_DIR/doom.symlink" "$HOME/.config/doom"
  doom sync

  doom env
else
  info 'Skipping doom setup'
fi

