#!/bin/bash

source helpers

ensure_command_exists brew

brew cask install iterm2

# Don't display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

exit 0
