#!/bin/sh
source helpers

check_homebrew

if test ! $(which clojure)
then
  info "Installing clojure and leiningen"
  brew install clojure leiningen

  info "Setting up lein profiles configuration"
  mkdir -p $HOME/.lein/
  CLOJURE_ROOT="$(cd "$(dirname "$0")" && pwd)"

  link_files $CLOJURE_ROOT/lein/profiles.clj $HOME/.lein/profiles.clj
  link_files $CLOJURE_ROOT/jokerd/linter.clj $HOME/.jokerd/linter.clj

  brew install candid82/brew/joker
  ln -f $CLOJURE_ROOT/joker.symlink $HOME/.joker

  brew install borkdude/brew/clj-kondo
fi

exit 0
