#!/bin/bash

source helpers

if command_exists lein; then
  mkdir -p "$HOME/.lein/"
  link_files "$(current_dir)/lein/profiles.clj" "$HOME/.lein/profiles.clj"
fi

if command_exists clojure-lsp; then
  if [ ! -h "$HOME/.lsp" ]; then
    link_files "$(current_dir)/lsp.symlink" "$HOME/.lsp"
  fi
fi
