#!/bin/sh
source helpers

check_homebrew

info 'Installing Redis'
brew install redis

info 'Setting up Redis LaunchAgent'
mkdir -p $HOME/Library/LaunchAgents
ln -sfv /usr/local/opt/redis/*.plist $HOME/Library/LaunchAgents
launchctl load $HOME/Library/LaunchAgents/homebrew.mxcl.redis.plist

exit 0
