#!/bin/bash

source "$DOTFILES_ROOT/print_helper"
source "$DOTFILES_ROOT/helpers"

ensure_command_exists "stow"

mkdir "$HOME/.nvm"

info "Setting up JS package"
run_required_step "Stowing npm package" stow npm
